# Site settings
title: My Portfolio
description: A showcase of my work and projects.
author: [Your Name]  # Replace with your actual name
email: your.email@example.com  # Replace with your actual email
url: "https://Arif5533.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave empty if hosted at root

# Build settings
theme: minima  # You can choose another theme if desired

# Social media links
social:
  github: https://github.com/Arif5533  # Replace with your GitHub profile URL
  linkedin: https://linkedin.com/in/your-profile  # Replace with your LinkedIn profile URL

# Plugins (optional)
plugins:
  - jekyll-feed  # For RSS feed support

# Markdown settings
markdown: kramdown

# Exclude files from being processed by Jekyll
exclude:
  - README.md  # Exclude if you are using an index.html instead

# Permalinks settings (optional)
permalink: pretty  # Use pretty permalinks for better SEO

# Customizing the layout (optional)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"  # Use default layout for all pages
